In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn as sl

In [2]:
data = pd.read_csv("C:\\Users\\amand\\OneDrive\\Desktop\\StudentsPerformance.csv")

In [3]:
data.head()

gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75

In [4]:
df= pd.DataFrame (data= data)

In [5]:
print(df)

     gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard   
1    female        group C                some college      standard   
2    female        group B             master's degree      standard   
3      male        group A          associate's degree  free/reduced   
4      male        group C                some college      standard   
..      ...            ...                         ...           ...   
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

    test preparation course  math score  reading score  writing score  
0                      none          72             72         

In [6]:
data.isna().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [7]:
import tensorflow as tf
from tensorflow import keras
from sklearn import metrics 
from sklearn import svm
from sklearn.metrics import accuracy_score

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64 
 6   reading score                1000 non-null   int64 
 7   writing score                1000 non-null   int64 
dtypes: int64(3), object(5)
memory usage: 62.6+ KB


In [10]:
data.describe().T

count    mean        std   min    25%   50%   75%    max
math score     1000.0  66.089  15.163080   0.0  57.00  66.0  77.0  100.0
reading score  1000.0  69.169  14.600192  17.0  59.00  70.0  79.0  100.0
writing score  1000.0  68.054  15.195657  10.0  57.75  69.0  79.0  100.0

In [13]:
x = pd.DataFrame(data[['reading score', 'writing score','math score']])
y = data['race/ethnicity']

In [14]:
x_train, x_test, y_train, y_test =train_test_split(x,y, test_size= 0.25)

In [25]:
print (x_train, y_train)

[[-0.17566677 -0.30027685  0.68305901]
 [-0.98893887 -1.02336035 -0.55405218]
 [-1.19225689 -1.68070898 -1.72605226]
 ...
 [ 0.23096927  0.62001123  1.39928127]
 [ 1.72196811  1.54029931  1.39928127]
 [ 1.11201404  1.93470849  1.20394793]] 656    group C
754    group C
11     group D
110    group D
574    group E
        ...   
736    group C
667    group B
144    group D
6      group B
652    group D
Name: race/ethnicity, Length: 750, dtype: object


In [34]:
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB

In [35]:
sc=StandardScaler()
x_train= sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [36]:
gnb=GaussianNB()

In [37]:
k= gnb.fit(x_train, y_train)

In [38]:
y_pred= gnb.predict(x_test)

In [39]:
print(y_pred[:25])

['group D' 'group C' 'group C' 'group C' 'group E' 'group D' 'group D'
 'group D' 'group E' 'group C' 'group C' 'group C' 'group D' 'group D'
 'group E' 'group E' 'group C' 'group C' 'group D' 'group C' 'group D'
 'group C' 'group C' 'group C' 'group E']


In [40]:
acc= accuracy_score(y_pred, y_test)

In [41]:
print(acc)

0.264


In [43]:
from sklearn.metrics import classification_report 

In [44]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

     group A       0.00      0.00      0.00        24
     group B       0.00      0.00      0.00        47
     group C       0.28      0.51      0.36        79
     group D       0.29      0.29      0.29        68
     group E       0.19      0.19      0.19        32

    accuracy                           0.26       250
   macro avg       0.15      0.20      0.17       250
weighted avg       0.19      0.26      0.22       250



C:\Users\amand\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\amand\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\amand\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [45]:
import pickle
# Open a file and use dump() 
with open('file_student.pkl', 'wb') as file: 
      
    # A new file will be created 
    pickle.dump(k, file)